# Usa la imagen oficial PHP con soporte FPM
FROM php:8.1-fpm

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    zip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Crear el directorio donde se clonará el repositorio
RUN mkdir /src

# Clonar el repositorio de GitHub dentro del directorio /src
RUN git clone https://github.com/tu_usuario/tu_repositorio.git /src

# Establecer el directorio de trabajo como /src
WORKDIR /src

# Copia el contenido de tu aplicación Laravel al contenedor
COPY . /var/www/html

# Instala las dependencias de Composer
RUN composer install

# Configura permisos para los directorios de Laravel
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

